### ISSUE TITLE
Implement linear search or binary search in Javascript using ES6

### ISSUE THREAD

**Issue by mandardeshpande** [frextrite/Data-Structures-Algorithms#7]

**Comment by mandardeshpande** [comment]
I would like to work on this.. if you are ok with it.

**Comment by frextrite** [comment]
@mandardeshpande sure, go ahead.

**Comment by connorphee** [comment]
Hello @frextrite , this looks to be stagnant, would I be able to work on this issue?

**Comment by frextrite** [comment]
@connorphee Just checked. Both algorithms are already implemented. I might've forgotten to close the issue. You can, however, work on any other data structure/algorithm that hasn't already been implemented, create an issue and start working on it.
